###
POST http://localhost:8080/api/admin/register HTTP/1.1
content-type: application/json

{
    "first_name": "Budi",
    "last_name": "Papa",
    "email": "b@p.com",
    "password": "123",
    "password_confirm": "123"
}


###
POST http://localhost:8080/api/admin/login HTTP/1.1
content-type: application/json

{
    "email": "b@p.com",
    "password": "123"
}


###
GET http://localhost:8080/api/admin/user HTTP/1.1



###
GET http://localhost:8080/api/admin/logout HTTP/1.1

###
PUT http://localhost:8080/api/admin/user/info HTTP/1.1
content-type: application/json

{
    "first_name": "Budiiiii",
    "last_name": "Papa",
    "email": "budi@p.com"
}

###
PUT http://localhost:8080/api/admin/user/password HTTP/1.1
content-type: application/json

{
    "password": "12",
    "password_confirm": "12"
}


###
GET http://localhost:8080/api/admin/ambassadors HTTP/1.1



###
POST http://localhost:8080/api/admin/products HTTP/1.1
content-type: application/json

{
    "title": "my title",
    "description": "this is about product trial",
    "image": "img.jpg",
    "price": 10
}

###
GET http://localhost:8080/api/admin/products HTTP/1.1



###
GET http://localhost:8080/api/admin/products/1 HTTP/1.1


###
PUT http://localhost:8080/api/admin/products/1 HTTP/1.1
content-type: application/json

{
    "title": "updated channel 44",
    "description": "updated",
    "image": "updated.jpg",
    "price": 99
}


###
DELETE  http://localhost:8080/api/admin/products/1 HTTP/1.1


###
GET http://localhost:8080/api/admin/users/3/links HTTP/1.1

###
GET http://localhost:8080/api/admin/orders HTTP/1.1


###
GET http://localhost:8080/api/admin/users/3/links HTTP/1.1

###
POST http://localhost:8080/api/ambassador/register HTTP/1.1
content-type: application/json

{
    "first_name": "Rapi",
    "last_name": "Amat",
    "email": "ra@ra.com",
    "password": "123",
    "password_confirm": "123"
}



###
POST http://localhost:8080/api/ambassador/login HTTP/1.1
content-type: application/json

{
    "email": "ra@ra.com",
    "password": "123"
}


###
GET http://localhost:8080/api/ambassador/user HTTP/1.1




###
GET http://localhost:8080/api/ambassador/products/frontend HTTP/1.1

###
GET http://localhost:8080/api/ambassador/products/backend HTTP/1.1


###
POST http://localhost:8080/api/ambassador/links HTTP/1.1
{
    "products": [2,3,5]
}